### ISSUE TITLE
Backend shut down caused by identity server 

### ISSUE THREAD

**Issue by JowieXiang** [micado-eu/micado_deployment#44]
While deploying `MICADO-1.1.4`, after everything is setup and have been running for a while, the backend shuts down unexpectedly. I am not sure which action caused the shut-down, but likely **a login action in the PA app**.

# Logs from backend: 

```
Pulling db_admin (dpage/pgadmin4:4.18)...
4.18: Pulling from dpage/pgadmin4
89d9c30c1d48: Pull complete
910c49c00810: Pull complete
7efe415eb85a: Pull complete
7d8d53519b81: Pull complete
519124ac136c: Pull complete
fbfa5cf626f8: Pull complete
f53a64187e16: Pull complete
feae0c230730: Pull complete
87ae2307a1ad: Pull complete
0a609eb1a1ca: Pull complete
b8bb05efc354: Pull complete
bccaa4da228f: Pull complete
084101fb937a: Pull complete
774874c72d7a: Pull complete
45a1fa7f66b7: Pull complete
b19cea40abf6: Pull complete
76e3d6803955: Pull complete
Digest: sha256:1141073018353f91953c1523f170821e139dbd1c2d7808d3804962b2ba7e89e3
Status: Downloaded newer image for dpage/pgadmin4:4.18
Recreating micado_micado_db_1 ... done
Creating micado_db_admin_1    ... done
[micadoadmin@micado-hh MICADO]$ docker logs micado_backend_1 
(node:1) ExperimentalWarning: The fs.promises API is experimental
SONO QUI
password1234567
{ name: 'micadoDS',
  connector: 'postgresql',
  url: 'postgres://micadoapp:micadoapp@micado_db/micado',
  host: 'micado_db',
  port: 5432,
  user: 'micadoapp',
  password: 'process.env.MICADO_DB_PWD',
  schema: 'micadoapp',
  migrationCreateSchema: false,
  database: 'micado' }
{ name: 'micadoDS',
  connector: 'postgresql',
  url: 'postgres://micadoapp:password1234567@micado_db/micado',
  host: 'micado_db',
  port: 5432,
  user: 'micadoapp',
  password: 'password1234567',
  schema: 'micadoapp',
  migrationCreateSchema: false,
  database: 'micado' }
Server is running at http://172.24.0.9:3000
Try http://172.24.0.9:3000/ping
Started Event Deleter Cron
Unpublishing events older than: 2021-04-17T09:37:00.181Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:38:00.276Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:39:00.540Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:40:00.752Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:41:00.819Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:42:00.893Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:43:00.966Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:44:00.034Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:45:00.132Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:46:00.200Z
Old events unpublished
in the identity controller retrieveTenants
IN RETRIEVE TENANT FUCNTION
prod
:9443
https://identity.micadohh.online:9443/services/TenantMgtAdminService?wsdl


micadoadm
password1234567
bWljYWRvYWRtOnBhc3N3b3JkMTIzNDU2Nw==
in the identity controller retrieveTenants
IN RETRIEVE TENANT FUCNTION
prod
:9443
https://identity.micadohh.online:9443/services/TenantMgtAdminService?wsdl
Unpublishing events older than: 2021-04-17T09:47:00.257Z
Old events unpublished
Unpublishing events older than: 2021-04-17T09:48:00.333Z
Old events unpublished
/home/node/app/dist/controllers/identity-tenant-manager.controller.js:72
                client.setSecurity(new soap.BasicAuthSecurity(process.env.WSO2_IDENTITY_ADMIN_USER, process.env.WSO2_IDENTITY_ADMIN_PWD));
                       ^

TypeError: Cannot read property 'setSecurity' of undefined
    at /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72:24
    at /home/node/app/node_modules/soap/lib/soap.js:84:9
    at /home/node/app/node_modules/soap/lib/soap.js:39:28
    at /home/node/app/node_modules/soap/lib/wsdl/index.js:1250:17
    at Request._callback (/home/node/app/node_modules/soap/lib/http.js:159:28)
    at self.callback (/home/node/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[micadoadmin@micado-hh MICADO]$ (set -a; source prod.env; set +a; docker-compose -f docker-compose-prod.yaml up -d backend)
Recreating micado_backend_1 ... done
[micadoadmin@micado-hh MICADO]$ IN RETRIEVE TENANT FUCNTION
-bash: IN: command not found
[micadoadmin@micado-hh MICADO]$ prod
-bash: prod: command not found
[micadoadmin@micado-hh MICADO]$ :9443
-bash: :9443: command not found
[micadoadmin@micado-hh MICADO]$ https://identity.micadohh.online:9443/services/TenantMgtAdminService?wsdl
-bash: https://identity.micadohh.online:9443/services/TenantMgtAdminService?wsdl: No such file or directory
[micadoadmin@micado-hh MICADO]$ Unpublishing events older than: 2021-04-17T09:47:00.257Z
-bash: Unpublishing: command not found
[micadoadmin@micado-hh MICADO]$ Old events unpublished
-bash: Old: command not found
[micadoadmin@micado-hh MICADO]$ Unpublishing events older than: 2021-04-17T09:48:00.333Z
-bash: Unpublishing: command not found
[micadoadmin@micado-hh MICADO]$ Old events unpublished
-bash: Old: command not found
[micadoadmin@micado-hh MICADO]$ /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72
-bash: /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72: No such file or directory
[micadoadmin@micado-hh MICADO]$                 client.setSecurity(new soap.BasicAuthSecurity(process.env.WSO2_IDENTITY_ADMIN_USER, process.env.WSO2_IDENTITY_ADMIN_PWD));
-bash: syntax error near unexpected token `new'
[micadoadmin@micado-hh MICADO]$                        ^
-bash: ^: command not found
[micadoadmin@micado-hh MICADO]$ 
[micadoadmin@micado-hh MICADO]$ TypeError: Cannot read property 'setSecurity' of undefined
-bash: TypeError:: command not found
[micadoadmin@micado-hh MICADO]$     at /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72:24
syntax error. Last token seen: /
Garbled time
[micadoadmin@micado-hh MICADO]$     at /home/node/app/node_modules/soap/lib/soap.js:84:9
syntax error. Last token seen: /
Garbled time
[micadoadmin@micado-hh MICADO]$     at /home/node/app/node_modules/soap/lib/soap.js:39:28
syntax error. Last token seen: /
Garbled time
[micadoadmin@micado-hh MICADO]$     at /home/node/app/node_modules/soap/lib/wsdl/index.js:1250:17
syntax error. Last token seen: /
Garbled time
[micadoadmin@micado-hh MICADO]$     at Request._callback (/home/node/app/node_modules/soap/lib/http.js:159:28)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at self.callback (/home/node/app/node_modules/request/request.js:185:22)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at Request.emit (events.js:198:13)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at ClientRequest.emit (events.js:198:13)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at TLSSocket.socketErrorListener (_http_client.js:392:9)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at TLSSocket.emit (events.js:198:13)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at emitErrorNT (internal/streams/destroy.js:91:8)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
-bash: syntax error near unexpected token `('
[micadoadmin@micado-hh MICADO]$     at process._tickCallback (internal/process/next_tick.js:63:19)
-bash: syntax error near unexpected token `('
```

**Comment by ivchicano** [comment]
You are having the same issue as I was having in https://github.com/micado-eu/backend/issues/29
I haven't tried to re deploy yet so I think it probably still doesn't work.

**Comment by gioppoluca** [comment]
Have you updated the compose file to the 1.1.4 and regenerated the identity container (--force-regenerate)?

**Comment by ivchicano** [comment]
Still not working, now with the following error when loging in
``

> backend_1             | (node:1) ExperimentalWarning: The fs.promises API is experimental
backend_1             | SONO QUI
backend_1             | RSwAbICtX3kep6hsrGFw
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:micadoapp@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'process.env.MICADO_DB_PWD',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:RSwAbICtX3kep6hsrGFw@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'RSwAbICtX3kep6hsrGFw',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | Server is running at http://172.24.0.9:3000
backend_1             | Try http://172.24.0.9:3000/ping
backend_1             | Started Event Deleter Cron
backend_1             | Unhandled error in GET /users?filter[include][0][relation]=attributes&filter[include][1][relation]=interventionPlans&filter[where][and][0][umUserName][eq]=admin&filter[where][and][1][umTenantId]=undefined&filter[fields]=umId: 500 error: invalid input syntax for integer: "undefined"
backend_1             |     at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:581:48)
backend_1             |     at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:380:19)
backend_1             |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:116:22)
backend_1             |     at Socket.emit (events.js:198:13)
backend_1             |     at addChunk (_stream_readable.js:288:12)
backend_1             |     at readableAddChunk (_stream_readable.js:269:11)
backend_1             |     at Socket.Readable.push (_stream_readable.js:224:10)
backend_1             |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by gioppoluca** [comment]
@ivchicano this is a different error from the one from @JowieXiang please let us try not to mix stuff or it will be difficult to solve it.
Also please state the flow that generated the problem: which application, which operation etc. or it will be impossible to understand anything (in your case seems to be login from the migrant application)

**Comment by gioppoluca** [comment]
@JowieXiang, as also @GiuseppeCSI told you, you need to use the updated 1.1.4 release files or you will never manage to fix the error.
Try the new version and if solved please colse the issue

**Comment by ivchicano** [comment]
Ok, I will open a new issue for this to keep it separated
